// {
//   "data": {
//     "prompt": "(masterpiece), best quality, expressive eyes, perfect face",
//     "model": "AbsoluteReality_v1.8.1.safetensors", // Ini modelnya
//     "lora": [ // Ini loranya, maksimal 5
//       "asamiya_athena:0.7"
//     ],
//     "negative_prompt": "(worst quality, low quality:1.4), (greyscale, monochrome:1.1), cropped, lowres , username, blurry, trademark, watermark, title, multiple view, Reference sheet, curvy, plump, fat, strabismus, clothing cutout, side slit,worst hand, (ugly face:1.2), extra leg, extra arm, bad foot, text, name",
//     "cfg": 7,
//     "request_from": 2
//   }
// }

// format loranya = ambil loraFilename:weight
// Contoh = CoveringBreasts_v1_left:1

const vA18 = [{
  loraFileName: "CoveringBreasts_v1_left",
  id: 142,
  name: "Covering breasts",
  description: "",
  type: 2,
  category: 6,
  weight: 1,
  prompt: "lora:covering-left-wasabiya",
  trigger_prompt: "naked boobs, coverl",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/98ed23010bce12625b1db47678905a6b.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/CoveringBreasts_v1_left.safetensors",
  status: 1,
  created_at: "2024-01-05 02:30:36",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "BreastsSqueezedTogether_v0.2",
  id: 361,
  name: "Breasts squeezed together",
  description: "",
  type: 2,
  category: 6,
  weight: 0.7,
  prompt: "lora:breasts_squeezed_together_v0.2",
  trigger_prompt: "breasts squeezed together, v arms, hands on own chest",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/0b698b02e481285587e878e1abfed9ef.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/BreastsSqueezedTogether_v0.2.safetensors",
  status: 1,
  created_at: "2024-05-16 08:33:36",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "PoolLadderConcept_v1",
  id: 372,
  name: "Concept Pool Ladder",
  description: "",
  type: 2,
  category: 6,
  weight: 1,
  prompt: "lora:Saya-pool leader4",
  trigger_prompt: "pool ladder,",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/1d95f9c08e0fcc7271d7c7322200efa8.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/PoolLadderConcept_v1.safetensors",
  status: 1,
  created_at: "2024-05-16 08:33:36",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "Garter_belts_v2",
  id: 92,
  name: "Garter belts",
  description: "",
  type: 2,
  category: 5,
  weight: 0.7,
  prompt: "lora:Garterbelt2",
  trigger_prompt: "garterbelt",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/c8ad15af7c4acb6f5784ad6ffa87b2bb.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/Garter_belts_v2.safetensors",
  status: 1,
  created_at: "2023-10-28 07:27:36",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "Crop_Tops_Strapless",
  id: 82,
  name: "Crop Tops",
  description: "",
  type: 2,
  category: 5,
  weight: 0.7,
  prompt: "lora:Bandeau-fC-V1",
  trigger_prompt: "bandeau",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/3099871b419d71afc9cd11c371fd1f55.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/Crop_Tops_Strapless.safetensors",
  status: 1,
  created_at: "2023-10-28 03:24:29",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "3DMM_v7",
  id: 16,
  name: "3D",
  description: "",
  type: 2,
  category: 2,
  weight: 0.7,
  prompt: "lora:3DMM_v7",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/6faf917618d922a80e6d53aec7af3896.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/3DMM_v7.safetensors",
  status: 1,
  created_at: "2023-07-05 01:20:15",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "add_detail",
  id: 17,
  name: "Detail",
  description: "",
  type: 2,
  category: 2,
  weight: 0.7,
  prompt: "lora:add_detail",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/ed3f8c62399d52cc72fceafe9ccd73d3.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/add_detail.safetensors",
  status: 1,
  created_at: "2023-07-05 01:20:27",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}];
const vA19 = [{
  loraFileName: "silver-wolf-v4-06",
  id: 1,
  name: "Silver Wolf",
  description: "",
  type: 2,
  category: 1,
  weight: 0.7,
  prompt: "lora:Sv4",
  trigger_prompt: "SilverWolfV5",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/b85596109e8904281ded43c5d51b71e0.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/silver-wolf-v4-06.safetensors",
  status: 1,
  created_at: "2023-07-05 01:17:03",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "Honkai: Star Rail",
  extra_data: "{}"
}, {
  loraFileName: "illya22outfits",
  id: 2,
  name: "Illya",
  description: "",
  type: 2,
  category: 1,
  weight: 0.7,
  prompt: "lora:illya22outfits",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/2e39f782a84b7fa7f8e6ba912023319e.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/illya22outfits.safetensors",
  status: 1,
  created_at: "2023-07-05 01:17:15",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "KafkaV4-06",
  id: 3,
  name: "Kafka",
  description: "",
  type: 2,
  category: 1,
  weight: 0.7,
  prompt: "lora:KafkaV4",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/0878aa7bff8e223f4c973e900a2ee1b2.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/KafkaV4-06.safetensors",
  status: 1,
  created_at: "2023-07-05 01:17:20",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "Honkai: Star Rail",
  extra_data: "{}"
}, {
  loraFileName: "asamiya_athena",
  id: 4,
  name: "Asamiya",
  description: "",
  type: 2,
  category: 1,
  weight: 0.7,
  prompt: "lora:asamiya_athena_3",
  trigger_prompt: "purple hair, long hair,hairband, ",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/25959fe41f3dccbcc99ccc58dd9be69f.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/asamiya_athena.safetensors",
  status: 1,
  created_at: "2023-07-05 01:17:25",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}];
const vA20 = [{
  loraFileName: "EnglishDollLikeness_v10",
  id: 43,
  name: "Realistic Doll V1",
  description: "",
  type: 2,
  category: 3,
  weight: 0.7,
  prompt: "lora:EnglishDollLikeness",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/6726f9a8c2c81c9f217a09db102fbaf5.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/EnglishDollLikeness_v10.safetensors",
  status: 1,
  created_at: "2023-07-21 10:47:19",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "taiwanDollLikeness_v20",
  id: 46,
  name: "Realistic Doll V2",
  description: "",
  type: 2,
  category: 3,
  weight: 0.7,
  prompt: "lora:taiwanDollLikeness_v20",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/f01c285780b435b426b7d750cfced00c.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/taiwanDollLikeness_v20.safetensors",
  status: 1,
  created_at: "2023-07-21 10:49:07",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "koreanDollLikeness",
  id: 45,
  name: "Doll",
  description: "",
  type: 2,
  category: 3,
  weight: 0.7,
  prompt: "lora:koreanDollLikeness",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/6a59853bf23cd02219945931242bd94a.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/koreanDollLikeness.safetensors",
  status: 1,
  created_at: "2023-07-21 10:48:27",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "JapaneseDollLikeness_v15",
  id: 49,
  name: "Realistic Doll V3",
  description: "",
  type: 2,
  category: 3,
  weight: 0.7,
  prompt: "lora:JapaneseDollLikeness_v15",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/292209697f3ed7fd90116c326d227826.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/JapaneseDollLikeness_v15.safetensors",
  status: 1,
  created_at: "2023-07-21 10:50:40",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}, {
  loraFileName: "Euro-AmericanDollLikeness_V20",
  id: 50,
  name: "Realistic Doll V4",
  description: "",
  type: 2,
  category: 3,
  weight: 0.7,
  prompt: "lora:new_whitegirls",
  trigger_prompt: "",
  preview: "https://animegenius-global.live3d.io/vtuber/ai_product/anime_genius/images/6f85932fed3de28b9a49bef0177cd5d5.webp",
  file_url: "https://live3d-global.uncledesk.com/vtuber/ai_product/anime_genius/models/Euro-AmericanDollLikeness_V20.safetensors",
  status: 1,
  created_at: "2023-07-21 10:51:26",
  updated_at: "2024-10-10 03:06:05",
  xl: 0,
  theme: "",
  extra_data: "{}"
}];
const vA21 = [{
  preview: "demo/ai-tools/webp/c7c73549ee9b453e3edc63d2c375b5cd_example1.webp",
  prompt: "(masterpiece), best quality, eyes to the viewer, expressive eyes, detailed eyes, crisp eyes, green eyes, lewd eyes, perfect face, (realistic face), smile, a Korean sexy young mom, messy hair, brunette, choker, (perfect body), (realistic body proportion), mature vibes, Exquisite white long dress suit, at home, exquisite suit clothes",
  model: "realistic"
}, {
  preview: "demo/ai-tools/webp/image/4463d255d88b38e9923890d62a788cf9_9caZQ_11zon.webp",
  prompt: "epic realistic, RAW, analog, A full portrait of stunning woman wearing swimsuit, alluring expression, swimming pool, clear water,  natural look, no make up,  masterpiece that captures the essence and beauty of the woman and water, ((highly detailed skin, skin details, water details)), sharp focus, volumetric fog, 8k UHD, DSLR, high quality, film grain, Fujifilm XT3,  soft cinematic light, adobe lightroom, photolab, hdr, intricate, highly detailed, (depth of field:1.4), faded, (neutral colors:1.2), (hdr:1.4), (muted colors:1.2), hyperdetailed, (artstation:1.4), cinematic, warm lights, dramatic light, (intricate details:1.1), complex background, (rutkowski:0.66), (teal and orange:0.4), (natural skin texture, hyperrealism, soft light, sharp),",
  model: "realistic"
}, {
  preview: "demo/ai-tools/webp/43fd8273c13f60d1bc5594bd9dbfd6c4TcAA_512_768.webp",
  prompt: "(masterpiece), best quality, expressive eyes, perfect face, girl,  rooftop, sunset, strong wind, overlooking,  mountains, trees, snow-capped mountains, heavy snow,  (Above the knee), smile",
  model: "anime"
}, {
  preview: "demo/ai-tools/webp/image/c02d7eaaa127f30e23e9156da3e85d58_JXqgAA_11zon.webp",
  prompt: "HDR, UHD, 8K, best quality, masterpiece, (masterpiece), best quality, expressive eyes, perfect face,safe_pos, Mesmerizing, close-up photograph of a stunning brunette woman walking gracefully along a tranquil Maldivian beach at sunset. The composition emphasizes her upper body, showcasing her radiant skin, long, intricately styled braid resting over her shoulder, and naturally full lips. She wears an elegant bikini top that subtly highlights her toned, athletic figure. Her confident posture conveys a sense of movement, hinting at her slow, relaxed stride.The warm, golden light of the setting sun bathes her features, creating a soft glow and natural highlights, while delicate shadows add depth to her skin’s texture. In the blurred background, gentle waves lap against the golden sand, reinforcing the serene atmosphere and framing her as the focal point of this ultra-realistic, cinematic scene. The photo captures an essence of sophistication and luxury, blending fashion photography aesthetics with the natural beauty of the moment. The mood is sensual yet tasteful, evoking a sense of effortless elegance and tranquility, sexy bikini, fit body, flat stomach, natural breast, (brunette, black hair), (looks sexy), (ultra realistic), meaty thighs, (erected nipples under clothing:0.7), (seductive), looks luxury, (looks elegant), (fashion style), ((fashion photographer style)),",
  model: "realistic"
}];